### ISSUE TITLE
Error on Check

### ISSUE THREAD

**Issue by TuRDMaN** [noiselabs/box-linux-sync#16]
I just did a git clone, then CD into the bin directory, and ran ./box-sync check

This is the error I got:

Traceback (most recent call last):
  File "./box-sync", line 47, in <module>
    from noiselabs.box.main import box_main
ImportError: No module named 'noiselabs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./box-sync", line 51, in <module>
    from noiselabs.box.main import box_main
  File "/home/user/box-linux-sync/src/noiselabs/**init**.py", line 22, in <module>
    **import**('pkg_resources').declare_namespace(**name**)
ImportError: No module named 'pkg_resources'

Any ideas? Could it be because of a python version mismatch?

**Comment by infinitemonkeytheorem** [comment]
@TuRDMaN . Thanks! This fix needs to be made even if you are running under virtualenv
